"""baseline schema

Revision ID: 0001
Revises:
Created: 2026-07-22 16:03:42.337138
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

import app.db.types
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guests",
        sa.Column("vmid", sa.Integer(), nullable=False),
        sa.Column("guest_type", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("node", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("backup_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "raw",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("first_seen_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint("guest_type IN ('vm', 'lxc')", name=op.f("ck_guests_guest_type_valid")),
        sa.CheckConstraint(
            "status IN ('running', 'stopped', 'unknown')", name=op.f("ck_guests_status_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guests")),
        sa.UniqueConstraint("node", "vmid", name="uq_guests_node_vmid"),
    )
    with op.batch_alter_table("guests", schema=None) as batch_op:
        batch_op.create_index("ix_guests_type_status", ["guest_type", "status"], unique=False)
        batch_op.create_index(batch_op.f("ix_guests_vmid"), ["vmid"], unique=False)

    op.create_table(
        "storage_snapshots",
        sa.Column("captured_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("local_total_bytes", sa.BigInteger(), nullable=False),
        sa.Column("local_used_bytes", sa.BigInteger(), nullable=False),
        sa.Column("local_free_bytes", sa.BigInteger(), nullable=False),
        sa.Column("remote_used_bytes", sa.BigInteger(), nullable=True),
        sa.Column("remote_quota_bytes", sa.BigInteger(), nullable=True),
        sa.Column("backup_count", sa.Integer(), nullable=False),
        sa.Column("oldest_backup_at", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_storage_snapshots")),
    )
    with op.batch_alter_table("storage_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_storage_snapshots_captured_at"), ["captured_at"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("last_login_ip", sa.String(length=45), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "role IN ('admin', 'operator', 'viewer')", name=op.f("ck_users_role_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "audit_events",
        sa.Column("ts", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("username_snapshot", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("result", sa.String(length=16), nullable=False),
        sa.Column("resource_type", sa.String(length=32), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column(
            "detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('login_success', 'login_failure', 'logout', 'token_refresh', 'token_reuse_detected', 'password_changed', 'account_locked', 'settings_changed', 'user_created', 'user_updated', 'user_deleted', 'backup_started', 'backup_deleted', 'restore_requested', 'restore_confirmed', 'retention_override')",
            name=op.f("ck_audit_events_action_valid"),
        ),
        sa.CheckConstraint(
            "result IN ('success', 'failure')", name=op.f("ck_audit_events_result_valid")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index("ix_audit_events_action_ts", ["action", "ts"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_events_correlation_id"), ["correlation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_events_ts"), ["ts"], unique=False)

    op.create_table(
        "backup_jobs",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("cron_expression", sa.String(length=64), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("compression", sa.String(length=16), nullable=False),
        sa.Column("zstd_threads", sa.Integer(), nullable=True),
        sa.Column("storage", sa.String(length=64), nullable=False),
        sa.Column("target_selector", sa.String(length=16), nullable=False),
        sa.Column("keep_local", sa.Integer(), nullable=False),
        sa.Column("keep_remote", sa.Integer(), nullable=False),
        sa.Column("upload_enabled", sa.Boolean(), nullable=False),
        sa.Column("notify_on_start", sa.Boolean(), nullable=False),
        sa.Column("notify_on_success", sa.Boolean(), nullable=False),
        sa.Column("notify_on_failure", sa.Boolean(), nullable=False),
        sa.Column("bwlimit_kbps", sa.Integer(), nullable=False),
        sa.Column("max_parallel", sa.Integer(), nullable=False),
        sa.Column("last_run_at", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("next_run_at", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column(
            "created_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "compression IN ('zstd', 'gzip', 'lzo', 'none')",
            name=op.f("ck_backup_jobs_compression_valid"),
        ),
        sa.CheckConstraint(
            "mode IN ('snapshot', 'suspend', 'stop')", name=op.f("ck_backup_jobs_mode_valid")
        ),
        sa.CheckConstraint(
            "target_selector IN ('all', 'include', 'exclude')",
            name=op.f("ck_backup_jobs_target_selector_valid"),
        ),
        sa.CheckConstraint(
            "keep_local >= 1", name=op.f("ck_backup_jobs_ck_backup_jobs_keep_local_positive")
        ),
        sa.CheckConstraint(
            "keep_remote >= 0", name=op.f("ck_backup_jobs_ck_backup_jobs_keep_remote_positive")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_backup_jobs_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backup_jobs")),
        sa.UniqueConstraint("name", name=op.f("uq_backup_jobs_name")),
    )
    with op.batch_alter_table("backup_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_backup_jobs_next_run_at"), ["next_run_at"], unique=False
        )

    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.String(length=64), nullable=False),
        sa.Column("expires_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("created_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
    )
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_refresh_tokens_family_id"), ["family_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_refresh_tokens_token_hash"), ["token_hash"], unique=True
        )
        batch_op.create_index(
            "ix_refresh_tokens_user_expiry", ["user_id", "expires_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_refresh_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "settings",
        sa.Column("section", sa.String(length=32), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column(
            "value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("value_type", sa.String(length=16), nullable=False),
        sa.Column("is_secret", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column(
            "updated_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("updated_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint(
            "section IN ('general', 'gdrive', 'telegram', 'retention', 'agent', 'proxmox')",
            name=op.f("ck_settings_section_valid"),
        ),
        sa.CheckConstraint(
            "value_type IN ('string', 'int', 'bool', 'json', 'secret')",
            name=op.f("ck_settings_value_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_settings_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
        sa.UniqueConstraint("section", "key", name="uq_settings_section_key"),
    )
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_settings_section"), ["section"], unique=False)

    op.create_table(
        "backup_job_targets",
        sa.Column("job_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("vmid", sa.Integer(), nullable=False),
        sa.Column("guest_type", sa.String(length=8), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint(
            "guest_type IN ('vm', 'lxc')", name=op.f("ck_backup_job_targets_guest_type_valid")
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["backup_jobs.id"],
            name=op.f("fk_backup_job_targets_job_id_backup_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backup_job_targets")),
        sa.UniqueConstraint("job_id", "vmid", name="uq_backup_job_targets_job_vmid"),
    )
    with op.batch_alter_table("backup_job_targets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_backup_job_targets_job_id"), ["job_id"], unique=False)

    op.create_table(
        "backup_runs",
        sa.Column("job_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "requested_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("guest_total", sa.Integer(), nullable=False),
        sa.Column("guest_succeeded", sa.Integer(), nullable=False),
        sa.Column("guest_failed", sa.Integer(), nullable=False),
        sa.Column("started_at", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("finished_at", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'success', 'partial', 'failed', 'cancelled', 'skipped_agent_unavailable')",
            name=op.f("ck_backup_runs_status_valid"),
        ),
        sa.CheckConstraint(
            "trigger IN ('schedule', 'manual', 'api')", name=op.f("ck_backup_runs_trigger_valid")
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["backup_jobs.id"],
            name=op.f("fk_backup_runs_job_id_backup_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name=op.f("fk_backup_runs_requested_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backup_runs")),
    )
    with op.batch_alter_table("backup_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_backup_runs_correlation_id"), ["correlation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_backup_runs_job_id"), ["job_id"], unique=False)
        batch_op.create_index(
            "ix_backup_runs_status_started", ["status", "started_at"], unique=False
        )

    op.create_table(
        "backup_history",
        sa.Column("run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("guest_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("vmid", sa.Integer(), nullable=False),
        sa.Column("guest_type", sa.String(length=8), nullable=False),
        sa.Column("guest_name", sa.String(length=128), nullable=False),
        sa.Column("node", sa.String(length=64), nullable=False),
        sa.Column("storage", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=True),
        sa.Column("local_path", sa.String(length=512), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("compression", sa.String(length=16), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("agent_task_id", sa.String(length=64), nullable=True),
        sa.Column("started_at", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("finished_at", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "warnings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("log_path", sa.String(length=512), nullable=True),
        sa.Column("upload_status", sa.String(length=16), nullable=False),
        sa.Column("uploaded_at", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("remote_path", sa.String(length=512), nullable=True),
        sa.Column("remote_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("remote_checksum", sa.String(length=64), nullable=True),
        sa.Column("retention_locked", sa.Boolean(), nullable=False),
        sa.Column("local_deleted_at", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("remote_deleted_at", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "compression IN ('zstd', 'gzip', 'lzo', 'none')",
            name=op.f("ck_backup_history_compression_valid"),
        ),
        sa.CheckConstraint(
            "guest_type IN ('vm', 'lxc')", name=op.f("ck_backup_history_guest_type_valid")
        ),
        sa.CheckConstraint(
            "mode IN ('snapshot', 'suspend', 'stop')", name=op.f("ck_backup_history_mode_valid")
        ),
        sa.CheckConstraint(
            "status IN ('running', 'success', 'failed', 'interrupted', 'deleted')",
            name=op.f("ck_backup_history_status_valid"),
        ),
        sa.CheckConstraint(
            "upload_status IN ('not_required', 'pending', 'uploading', 'uploaded', 'failed')",
            name=op.f("ck_backup_history_upload_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["guest_id"],
            ["guests.id"],
            name=op.f("fk_backup_history_guest_id_guests"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["backup_runs.id"],
            name=op.f("fk_backup_history_run_id_backup_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backup_history")),
        sa.UniqueConstraint("storage", "filename", name="uq_backup_history_storage_filename"),
    )
    with op.batch_alter_table("backup_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_backup_history_agent_task_id"), ["agent_task_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_backup_history_correlation_id"), ["correlation_id"], unique=False
        )
        batch_op.create_index(
            "ix_backup_history_guest_started", ["vmid", "guest_type", "started_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_backup_history_run_id"), ["run_id"], unique=False)
        batch_op.create_index("ix_backup_history_status", ["status"], unique=False)
        batch_op.create_index("ix_backup_history_upload_status", ["upload_status"], unique=False)

    op.create_table(
        "restore_history",
        sa.Column(
            "backup_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("target_vmid", sa.Integer(), nullable=False),
        sa.Column("target_type", sa.String(length=8), nullable=False),
        sa.Column("restore_mode", sa.String(length=16), nullable=False),
        sa.Column("target_node", sa.String(length=64), nullable=False),
        sa.Column("target_storage", sa.String(length=64), nullable=False),
        sa.Column("overwrite_existing", sa.Boolean(), nullable=False),
        sa.Column("force_stop", sa.Boolean(), nullable=False),
        sa.Column("start_after_restore", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("confirmation_token_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "confirmation_expires_at", app.db.types.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("confirmed_at", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column(
            "preflight",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("agent_task_id", sa.String(length=64), nullable=True),
        sa.Column(
            "requested_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("started_at", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("finished_at", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("log_path", sa.String(length=512), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint(
            "restore_mode IN ('original_id', 'new_id')",
            name=op.f("ck_restore_history_restore_mode_valid"),
        ),
        sa.CheckConstraint(
            "source IN ('local', 'gdrive')", name=op.f("ck_restore_history_source_valid")
        ),
        sa.CheckConstraint(
            "status IN ('pending_confirmation', 'confirmed', 'running', 'success', 'failed', 'cancelled', 'expired')",
            name=op.f("ck_restore_history_status_valid"),
        ),
        sa.CheckConstraint(
            "target_type IN ('vm', 'lxc')", name=op.f("ck_restore_history_target_type_valid")
        ),
        sa.ForeignKeyConstraint(
            ["backup_id"],
            ["backup_history.id"],
            name=op.f("fk_restore_history_backup_id_backup_history"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name=op.f("fk_restore_history_requested_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_restore_history")),
    )
    with op.batch_alter_table("restore_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_restore_history_agent_task_id"), ["agent_task_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_restore_history_backup_id"), ["backup_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_restore_history_correlation_id"), ["correlation_id"], unique=False
        )
        batch_op.create_index(
            "ix_restore_history_status_created", ["status", "created_at"], unique=False
        )

    op.create_table(
        "retention_events",
        sa.Column("backup_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("vmid", sa.Integer(), nullable=False),
        sa.Column("guest_type", sa.String(length=8), nullable=False),
        sa.Column("action", sa.String(length=24), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column(
            "policy_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("freed_bytes", sa.BigInteger(), nullable=False),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('evaluated', 'kept', 'deleted_local', 'deleted_remote', 'skipped', 'failed')",
            name=op.f("ck_retention_events_action_valid"),
        ),
        sa.CheckConstraint(
            "guest_type IN ('vm', 'lxc')", name=op.f("ck_retention_events_guest_type_valid")
        ),
        sa.ForeignKeyConstraint(
            ["backup_id"],
            ["backup_history.id"],
            name=op.f("fk_retention_events_backup_id_backup_history"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retention_events")),
    )
    with op.batch_alter_table("retention_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_retention_events_guest_created", ["vmid", "guest_type", "created_at"], unique=False
        )

    op.create_table(
        "sync_tasks",
        sa.Column("backup_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("agent_task_id", sa.String(length=64), nullable=True),
        sa.Column("remote_name", sa.String(length=64), nullable=True),
        sa.Column("remote_path", sa.String(length=512), nullable=True),
        sa.Column("bytes_total", sa.BigInteger(), nullable=True),
        sa.Column("bytes_transferred", sa.BigInteger(), nullable=False),
        sa.Column("transfer_rate_bps", sa.BigInteger(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("started_at", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("finished_at", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint(
            "direction IN ('upload', 'download', 'verify')",
            name=op.f("ck_sync_tasks_direction_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'success', 'failed', 'cancelled')",
            name=op.f("ck_sync_tasks_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["backup_id"],
            ["backup_history.id"],
            name=op.f("fk_sync_tasks_backup_id_backup_history"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_tasks")),
    )
    with op.batch_alter_table("sync_tasks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sync_tasks_agent_task_id"), ["agent_task_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sync_tasks_backup_id"), ["backup_id"], unique=False)
        batch_op.create_index(
            "ix_sync_tasks_status_created", ["status", "created_at"], unique=False
        )

    op.create_table(
        "logs",
        sa.Column("ts", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("level", sa.String(length=8), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "context",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("backup_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column(
            "restore_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "sync_task_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('api', 'backup', 'restore', 'upload', 'retention', 'scheduler', 'auth', 'agent', 'system')",
            name=op.f("ck_logs_category_valid"),
        ),
        sa.CheckConstraint(
            "level IN ('debug', 'info', 'warning', 'error', 'critical')",
            name=op.f("ck_logs_level_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["backup_id"],
            ["backup_history.id"],
            name=op.f("fk_logs_backup_id_backup_history"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["restore_id"],
            ["restore_history.id"],
            name=op.f("fk_logs_restore_id_restore_history"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sync_task_id"],
            ["sync_tasks.id"],
            name=op.f("fk_logs_sync_task_id_sync_tasks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_logs_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_logs")),
    )
    with op.batch_alter_table("logs", schema=None) as batch_op:
        batch_op.create_index("ix_logs_category_ts", ["category", "ts"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_logs_correlation_id"), ["correlation_id"], unique=False
        )
        batch_op.create_index("ix_logs_level_ts", ["level", "ts"], unique=False)
        batch_op.create_index(batch_op.f("ix_logs_ts"), ["ts"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("sent_at", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("backup_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column(
            "restore_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint("channel IN ('telegram')", name=op.f("ck_notifications_channel_valid")),
        sa.CheckConstraint(
            "event_type IN ('backup_started', 'backup_success', 'backup_failed', 'restore_started', 'restore_finished', 'restore_failed', 'upload_failed', 'retention_deleted', 'storage_threshold', 'test')",
            name=op.f("ck_notifications_event_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'sent', 'failed', 'suppressed')",
            name=op.f("ck_notifications_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["backup_id"],
            ["backup_history.id"],
            name=op.f("fk_notifications_backup_id_backup_history"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["restore_id"],
            ["restore_history.id"],
            name=op.f("fk_notifications_restore_id_restore_history"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            "ix_notifications_status_created", ["status", "created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index("ix_notifications_status_created")

    op.drop_table("notifications")
    with op.batch_alter_table("logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_logs_ts"))
        batch_op.drop_index("ix_logs_level_ts")
        batch_op.drop_index(batch_op.f("ix_logs_correlation_id"))
        batch_op.drop_index("ix_logs_category_ts")

    op.drop_table("logs")
    with op.batch_alter_table("sync_tasks", schema=None) as batch_op:
        batch_op.drop_index("ix_sync_tasks_status_created")
        batch_op.drop_index(batch_op.f("ix_sync_tasks_backup_id"))
        batch_op.drop_index(batch_op.f("ix_sync_tasks_agent_task_id"))

    op.drop_table("sync_tasks")
    with op.batch_alter_table("retention_events", schema=None) as batch_op:
        batch_op.drop_index("ix_retention_events_guest_created")

    op.drop_table("retention_events")
    with op.batch_alter_table("restore_history", schema=None) as batch_op:
        batch_op.drop_index("ix_restore_history_status_created")
        batch_op.drop_index(batch_op.f("ix_restore_history_correlation_id"))
        batch_op.drop_index(batch_op.f("ix_restore_history_backup_id"))
        batch_op.drop_index(batch_op.f("ix_restore_history_agent_task_id"))

    op.drop_table("restore_history")
    with op.batch_alter_table("backup_history", schema=None) as batch_op:
        batch_op.drop_index("ix_backup_history_upload_status")
        batch_op.drop_index("ix_backup_history_status")
        batch_op.drop_index(batch_op.f("ix_backup_history_run_id"))
        batch_op.drop_index("ix_backup_history_guest_started")
        batch_op.drop_index(batch_op.f("ix_backup_history_correlation_id"))
        batch_op.drop_index(batch_op.f("ix_backup_history_agent_task_id"))

    op.drop_table("backup_history")
    with op.batch_alter_table("backup_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_backup_runs_status_started")
        batch_op.drop_index(batch_op.f("ix_backup_runs_job_id"))
        batch_op.drop_index(batch_op.f("ix_backup_runs_correlation_id"))

    op.drop_table("backup_runs")
    with op.batch_alter_table("backup_job_targets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_backup_job_targets_job_id"))

    op.drop_table("backup_job_targets")
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_settings_section"))

    op.drop_table("settings")
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_user_id"))
        batch_op.drop_index("ix_refresh_tokens_user_expiry")
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_token_hash"))
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_family_id"))

    op.drop_table("refresh_tokens")
    with op.batch_alter_table("backup_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_backup_jobs_next_run_at"))

    op.drop_table("backup_jobs")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_ts"))
        batch_op.drop_index(batch_op.f("ix_audit_events_correlation_id"))
        batch_op.drop_index("ix_audit_events_action_ts")

    op.drop_table("audit_events")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    with op.batch_alter_table("storage_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_storage_snapshots_captured_at"))

    op.drop_table("storage_snapshots")
    with op.batch_alter_table("guests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_guests_vmid"))
        batch_op.drop_index("ix_guests_type_status")

    op.drop_table("guests")
    # ### end Alembic commands ###
