#!/usr/bin/env bash
#
# One-shot development setup for ProxSync.
#
# Idempotent and safe to re-run: it creates the three virtualenvs if missing, writes dev
# `.env` files for the backend and agent (with generated secrets, and a *shared* HMAC so the
# two can actually talk), and applies the database migrations. It never overwrites an existing
# `.env` unless you pass --force, so your local tweaks survive a re-run.
#
#   ./scripts/dev-setup.sh [--force]
#
# This is for local development only. It configures the backend for http (COOKIE_SECURE=false)
# and the agent without TLS — neither is safe outside your machine.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

FORCE=0
[[ "${1:-}" == "--force" ]] && FORCE=1

log()  { printf '\033[0;36m[dev-setup]\033[0m %s\n' "$*"; }
warn() { printf '\033[0;33m[dev-setup]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[0;31m[dev-setup]\033[0m %s\n' "$*" >&2; exit 1; }

command -v openssl >/dev/null || die "openssl is required."

# ---- Virtualenvs / deps ----------------------------------------------------
if [[ ! -x backend/.venv/bin/python ]]; then
    log "Installing backend dependencies"
    make backend-install
else
    log "backend venv present — skipping (delete backend/.venv to reinstall)"
fi

if [[ ! -x agent/.venv/bin/python ]]; then
    log "Installing agent dependencies"
    make agent-install
else
    log "agent venv present — skipping"
fi

if [[ ! -d frontend/node_modules ]]; then
    log "Installing frontend dependencies"
    make frontend-install
else
    log "frontend node_modules present — skipping"
fi

# A single HMAC shared by both sides so the dashboard→agent signature verifies in dev.
SHARED_HMAC="$(openssl rand -hex 32)"

# ---- backend/.env ----------------------------------------------------------
if [[ -f backend/.env && $FORCE -eq 0 ]]; then
    log "backend/.env exists — keeping it (pass --force to regenerate)"
else
    log "Writing backend/.env"
    cat > backend/.env <<EOF
# Generated by scripts/dev-setup.sh on $(date -Is) — DEVELOPMENT ONLY.
PROXSYNC_ENVIRONMENT=development
PROXSYNC_BIND_HOST=127.0.0.1
PROXSYNC_BIND_PORT=8000
PROXSYNC_LOG_LEVEL=INFO
PROXSYNC_LOG_JSON=false

# http in dev, so session cookies cannot be Secure-only.
PROXSYNC_COOKIE_SECURE=false

PROXSYNC_SECRET_KEY=$(openssl rand -hex 32)
PROXSYNC_DATABASE_URL=sqlite+aiosqlite:///./proxsync-dev.db

# Same-origin via the Next.js dev proxy, so CORS is left at its default (empty list).
# NOTE: do not write PROXSYNC_CORS_ORIGINS= here — an empty string is JSON-parsed for this
# list field before the CSV validator runs, and json.loads("") raises. Omit it instead.

# First-run administrator. Change the password at first login.
PROXSYNC_BOOTSTRAP_ADMIN_USERNAME=admin
PROXSYNC_BOOTSTRAP_ADMIN_PASSWORD=admin123

# Backup Agent (optional in dev). The agent below runs without TLS, so point at http and
# don't verify a certificate. Leave HMAC empty to run the dashboard with no agent at all.
PROXSYNC_AGENT_BASE_URL=http://127.0.0.1:8765
PROXSYNC_AGENT_VERIFY_TLS=false
PROXSYNC_AGENT_API_KEY_ID=proxsync-dashboard
PROXSYNC_AGENT_HMAC_SECRET=${SHARED_HMAC}
EOF
fi

# ---- agent/.env ------------------------------------------------------------
if [[ -f agent/.env && $FORCE -eq 0 ]]; then
    log "agent/.env exists — keeping it (pass --force to regenerate)"
else
    log "Writing agent/.env"
    # Reuse the backend's HMAC if we kept an existing backend/.env, so they always match.
    if [[ -f backend/.env ]]; then
        EXISTING="$(grep -E '^PROXSYNC_AGENT_HMAC_SECRET=' backend/.env | cut -d= -f2-)"
        [[ -n "$EXISTING" ]] && SHARED_HMAC="$EXISTING"
    fi
    cat > agent/.env <<EOF
# Generated by scripts/dev-setup.sh on $(date -Is) — DEVELOPMENT ONLY (no TLS).
PROXSYNC_AGENT_BIND_HOST=127.0.0.1
PROXSYNC_AGENT_BIND_PORT=8765
PROXSYNC_AGENT_LOG_LEVEL=INFO
PROXSYNC_AGENT_LOG_JSON=false

# No mTLS in dev: the agent is reachable only from localhost.
PROXSYNC_AGENT_ALLOWED_CLIENT_NETWORKS=127.0.0.1/32

PROXSYNC_AGENT_API_KEY_ID=proxsync-dashboard
PROXSYNC_AGENT_HMAC_SECRET=${SHARED_HMAC}
PROXSYNC_AGENT_SIGNATURE_WINDOW_SECONDS=60

# Local scratch dirs so the agent has somewhere to write without root.
PROXSYNC_AGENT_DUMP_ROOT=$ROOT/.dev/agent/dump
PROXSYNC_AGENT_TEMP_DIR=$ROOT/.dev/agent/tmp
PROXSYNC_AGENT_STATE_DIR=$ROOT/.dev/agent/state
PROXSYNC_AGENT_LOG_DIR=$ROOT/.dev/agent/log

PROXSYNC_AGENT_ALLOWED_BACKUP_STORAGES=
PROXSYNC_AGENT_VERIFY_STORAGE_WITH_PVESM=false
PROXSYNC_AGENT_SYNC_ENABLED=false
EOF
    mkdir -p "$ROOT/.dev/agent/dump" "$ROOT/.dev/agent/tmp" "$ROOT/.dev/agent/state" "$ROOT/.dev/agent/log"
fi

# ---- Database --------------------------------------------------------------
log "Applying database migrations"
( cd backend && set -a && . .env && set +a && .venv/bin/alembic upgrade head )

log "Done. Start everything with:  make dev"
log "  dashboard  http://localhost:3000   (login admin / admin123)"
log "  api        http://127.0.0.1:8000"
log "  agent      http://127.0.0.1:8765   (no TLS, dev only)"
